import Head from "next/head";
import Food from "@/components/pages/foods/Food"
import MainLayout from "@/components/common/layouts/MainLayout";
import FoodDiogramma from "@/components/pages/foods/FoodDiogramma"
import styles from "@/styles/Home.module.css";

export default function Foods() {
  return (
    <>
      <Head>
        <title>Foods</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Food />
        <FoodDiogramma/>
      </div>
    </>
  );
}

Foods.getLayout = (pageProps) => (
  <MainLayout>
    <Foods {...pageProps} />
  </MainLayout>
);
