import Head from "next/head";
import OrderDetail from "@/components/pages/orders/OrderDetail"
import MainLayout from "@/components/common/layouts/MainLayout";
import styles from "@/styles/Home.module.css";

export default function Order_Detail() {
  return (
    <>
      <Head>
        <title>Cutomers List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <OrderDetail />
      </div>
    </>
  );
}

Order_Detail.getLayout = (pageProps) => (
  <MainLayout>
    <Order_Detail {...pageProps} />
  </MainLayout>
);
